### PR TITLE
refactor(docs): move Dockerfile-docs to the right directory

### PR DESCRIPTION
**Pull request by PopBogdan97**
Fixing docs' dockerfile location

### CODE REVIEW

**Comment by zanna-37** [comment]
TODO:
- [ ] fix #17
- [ ] fix #18

**Comment by zanna-37** [comment]
fixes: #17 #18

**Review by zanna-37 — APPROVED** [review]
If you agree on the fixes you can merge it.

**Review by PopBogdan97 — COMMENTED** [review]
All right

**Review by PopBogdan97 — COMMENTED** [review]
All right

**Pull request merged**
